#ifndef FBC_FACE_TEST_TADAS_OPENFACE_FUNSET_HPP_
#define FBC_FACE_TEST_TADAS_OPENFACE_FUNSET_HPP_

int test_FaceDetect_HOG();
int test_FaceDetect_HaarCascade();

#endif // FBC_FACE_TEST_TADAS_OPENFACE_FUNSET_HPP_
